apiVersion: v1
kind: Service
metadata:
  namespace: oss-k8s-demo
  name: color-webapp-service-v2
  labels: 
    app: color-webapp
    version: green
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30121
  selector: 
    app: color-webapp
    version: green
  type: NodePort
