apiVersion: v1
kind: Service
metadata:
  namespace: oss-k8s-demo
  name: color-webapp-service
  labels: 
    app: color-webapp
    version: blue
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30120
  selector: 
    app: color-webapp
    version: blue
  type: NodePort
