apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: oss-k8s-demo
  name: color-webapp-deploy-v2
  labels:
    app: color-webapp
    version: green
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: color-webapp
      version: green
  replicas: 10
  template:
    metadata:
      labels:
        app: color-webapp
        version: green
    spec:
      containers:
        - name: color-webapp
          image: kodekloud/simple-webapp:green
          ports:
          - containerPort: 8080
