apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: oss-k8s-demo
  name: color-webapp-deploy
  labels:
    version: blue
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: color-webapp
      version: blue
  replicas: 4
  template:
    metadata:
      labels:
        app: color-webapp
        version: blue
    spec:
      containers:
        - name: color-webapp
          image: kodekloud/simple-webapp:blue
          ports:
          - containerPort: 8080
